version: "3"
services:
  db:
    container_name: blogs-api
    image: mysql:8.0
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blogs_api
    volumes:
      - ./data:/var/lib/mysql
