// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package blogs

import (
	"database/sql"
)

type User struct {
	ID          uint64
	DisplayName string
	Email       string
	Password    string
	Image       sql.NullString
}
